version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - common-net
  mysqldb-blog-service:
    container_name: 'mysqldb-blog-service'
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "BLOG-DB"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      timeout: 20s
      retries: 10
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - common-net
  mysqldb-chat-service:
    container_name: 'mysqldb-chat-service'
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "CHAT-DB"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      timeout: 20s
      retries: 10
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - common-net
  mysqldb-email-service:
    container_name: 'mysqldb-email-service'
    image: mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "EMAIL-DB"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      timeout: 20s
      retries: 10
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - common-net
  mysqldb-notification-service:
    container_name: 'mysqldb-notification-service'
    image: mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "NOTIFICATION-DB"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      timeout: 20s
      retries: 10
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - common-net
  mysqldb-user-service:
    container_name: 'mysqldb-user-service'
    image: mysql
    ports:
      - "3311:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "USER-DB"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      timeout: 20s
      retries: 10
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - common-net
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - common-net
networks:
  common-net:
    driver: bridge
